### ISSUE TITLE
Store only changed data?

### ISSUE THREAD

**Issue by efleming** [bitcrowd/carbonite#119]
Is it possible to only store the data that is changed and not the entire data struct?

Example, I update a flag for a feature. I only want to store the original value and the new value. I don't need the entire data struct.

**Comment by maltoe** [comment]
Hi @efleming,

no, this is not possible and intentionally so. The idea was to have a "version history" of entities where versions could be easily forwarded to other systems. If we stored only deltas, computing a "version" would require fetching the entire previous history, which we didn't want.

That said, your `changes` table is an ordinary Ecto table, you could write a processor that trims the `data` field according to your needs. See https://hexdocs.pm/carbonite/Carbonite.html#process/4

Hope this helps.
