### ISSUE TITLE
Track replaced data in changes

### ISSUE THREAD

**Issue by ssbb** [bitcrowd/carbonite#51]
Hi! Thank you for such awesome library.  

I have a question regarding workflow with old data. I have a lot of records in database already and don't want to lose any changes history. 

So my problem is: when I'll integrate Carbonite into existing table and it will track first change (eg record updated) - I'll don't know what data I had before this update. (since there it no initial `insert` transaction).

I saw in earlier versions you stored both new and old data so it was possible to make DIFF based on it. But then you deleted old data for some reason.

So what I suggested workflow here? Should I backfill my transactions/changes from existing data? Or there any better options?

Thank you!

**Comment by maltoe** [comment]
Hi @ssbb Thanks for your kind words.

TBH I don't quite remember the exact reasons for changing `new/old` into `data/changed` - waste of storage space perhaps. Feels like a relatively poor choice in hindsight. Let me see if I can fix this.

**Comment by ssbb** [comment]
> Hi @ssbb Thanks for your kind words.
> 
> TBH I don't quite remember the exact reasons for changing `new/old` into `data/changed` - waste of storage space perhaps. Feels like a relatively poor choice in hindsight. Let me see if I can fix this.

Oh thank you, it looks fantastic! Looks like much better solution than backfilling transactions/changes from existing data. Had no idea you will just do it ❤️

Just thinking - do you think it will make sense to add same option for `delete` as well? I can try to prepare PR later

**Comment by maltoe** [comment]
@ssbb :thinking: For `DELETE` we already record the entire record in `data` - or maybe I don't get what you mean?

**Comment by ssbb** [comment]
Yeah sorry my fault :) 

Thank you a lot again!
