### ISSUE TITLE
When store_changed_from is enabled,  the filtered_columns is ignored on copied data

### ISSUE THREAD

**Issue by xadhoom** [bitcrowd/carbonite#96]
Hi,

seems that when `store_changed_from` is enabled, the `filtered_columns` option is applied only on data and not on copied data. So if for example you filter out the `password` column, in the data column of changes is correctly saved like `"password": "[FILTERED]"`, while in the `changed_from`  the old value is present.

Probably should be filtered also in the previous data column?

**Comment by maltoe** [comment]
Hi @xadhoom 

thank you for reporting! :purple_heart: This is a pretty mean bug for the ones affected. Let's hope that this did not ruins peoples' day. :crossed_fingers:

**Comment by maltoe** [comment]
Fixed in v0.12.0
